image: Visual Studio 2019

init:
  - git config --global core.autocrlf input

before_build:
  - git submodule init
  - git submodule update

build_script:
  - dotnet build RpdPatcher
  - dotnet build AdcEditor
  - dotnet build ReviewGenerator

test: off
